config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :vaccines do
    resources :reservations
  end
  get 'dashboard', to: 'dashboard#dashboard', as: 'dashboard'
  patch "reservations/:id/confirm", to: 'dashboard#confirm', as: 'reservation_confirm'
  patch "reservations/:id/cancel", to: 'dashboard#cancel', as: 'reservation_cancel'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :vaccine
  belongs_to :user
  validates :status, inclusion: { in: ['Pending', 'Confirmed', 'Cancelled'] }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :vaccines
  has_many :reservations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/models/vaccine.rb
class Vaccine < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
    against: [ :name, :description ],
    using: {
      tsearch: { prefix: true }
    }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: [:index, :dashboard], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:index, :dashboard], unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def dashboard
    # Vaccines you have listed
    @vaccines = policy_scope(Vaccine).where(user: current_user)

    # Vaccines you have reserved(booked)
    @reservations = policy_scope(Reservation).where(user: current_user)

    # Reservations for your vaccines
    # Find all reservations where the owner of the vaccine is the current_user
    @reservations_for_seller = []
    @vaccines.each do |vaccine|
      vaccine.reservations.each do |reservation|
        @reservations_for_seller << reservation
      end
    end
  end

  def confirm
    @reservation = Reservation.find(params[:id])
    @reservation.status = 'Confirmed'
    @reservation.save
    redirect_to dashboard_path
    authorize @reservation
  end

  def cancel
    @reservation = Reservation.find(params[:id])
    @reservation.status = 'Cancelled'
    @reservation.save
    redirect_to dashboard_path
    authorize @reservation
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home]
  def home
      @vaccines = policy_scope(Vaccine)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_action :require_login

  def new
    @vaccine = Vaccine.find(params[:vaccine_id])
    @user = current_user
    @reservation = Reservation.new
    authorize @reservation
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @vaccine = Vaccine.find(params[:vaccine_id])
    @reservation.status = 'Pending'
    @user = current_user
    @reservation.vaccine = @vaccine
    @reservation.user = @user
    @reservation.save

    # Temporary redirect until the history page is created
    redirect_to vaccine_path(@vaccine)
    authorize @reservation
  end

  private

  def reservation_params
    params.require(:reservation).permit(:date)
  end

  def require_login
    unless current_user
      redirect_to new_user_session_path
    end
  end
end

app/controllers/vaccines_controller.rb
class VaccinesController < ApplicationController

  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @vaccines = policy_scope(Vaccine.search_by_name_and_description(params[:query]))
     else
      @vaccines = policy_scope(Vaccine)
     end
  end

  def show
    @vaccine = Vaccine.find(params[:id])
    authorize @vaccine
    # @reservation = Reservation.find(params[@vaccine.id])
  end

  def new
    @vaccine = Vaccine.new
    authorize @vaccine
  end

  def create
    @vaccine = Vaccine.new(vaccine_params)
    @vaccine.user = current_user
    if @vaccine.save
      redirect_to vaccine_path(@vaccine)
    else
      render :new
    end
    authorize @vaccine
  end

  def edit
  end

  def update
    if @vaccine.update(vaccine_params)
      redirect_to vaccine_path(@vaccine), notice: "Vaccine was successfully updated"
    else
      render :edit
    end
    authorize @vaccine
  end

  def destroy
    @vaccine.destroy
    redirect_to vaccines_path, notice: "Vaccine was successfully deleted"
  end

  private

  def find_vaccine
    @vaccine = Vaccine.find(params[:id])
    authorize @vaccine
  end

  def vaccine_params
    params.require(:vaccine).permit(:name, :description, :photo, :query)
  end

  def require_login
    unless current_user
      redirect_to new_user_session_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/dashboard.html.erb
<div class="container">
  <%= render 'shared/vaccines-table' %>
  <%= render 'shared/reservations-for-seller-table' %>
  <%= render 'shared/reservations-table' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CleanVaccine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner"></div>
<div class="container">
  <h1>Newest</h1>
  <p><%= link_to "See our newest 🔥 vaccines", vaccines_path%></p>
  <ul>
    <% @vaccines[0..4].each do |vaccine| %>
      <div class="card-product">
        <% if vaccine.photo.attached? %>
          <%= cl_image_tag vaccine.photo.key, height: 300, width: 400, crop: :fill %>
        <% else %>
          <img src="https://source.unsplash.com/CMLL0UD6AEE/300x400">
        <% end %>
        <div class="card-product-infos">
          <h2><%= link_to vaccine.name, vaccine_path(vaccine) %></h2>
          <p><%= vaccine.description %></strong></p>
        </div>
      </div>
    <% end %>
  </ul>
</div>
<div class="hero-image">
  <div class="hero-text">
    <h1>Get a free second dose</h1>
    <p>Refer a friend by putting his social insurance number and get a free dose 👽</p>
    <li class="search-bar">
      <%= form_tag root_path, style: 'display: flex', method: :get do %>
      <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Social #" %>
      <% end %>
    </li>
  </div>
</div>

<!-- style="background-image: url(#{image_path 'banner-clean-vaccine.jpg'})" -->

app/views/reservations/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Reserve Vaccine: <%= @vaccine.name %></h1>

      <%= simple_form_for [ @vaccine, @reservation ] do |f| %>
        <%= f.input :date, as: :string, input_html: {type: :date}, label: 'Your reservation date:' %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
   ©2021 CleanVaccine, Inc. made using WIX
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo-eye.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="search-bar">
          <%= form_tag vaccines_path, style: 'display: flex', method: :get do %>
            <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Find a vaccine" %>
            <%= submit_tag "Search", class: "btn btn-primary" %>
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Vaccines", vaccines_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "user-default.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Create", new_vaccine_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_reservations-for-seller-table.html.erb
<h1>Reservations for your vaccines</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Vaccine name</th>
      <th scope="col">User</th>
      <th scope="col">Date</th>
      <th scope="col">Confirmation</th>
    </tr>
  </thead>
  <tbody>
    <% @reservations_for_seller.each do |reservation| %>
      <tr>
        <th scope="row"><%= reservation.id %></th>
        <td><%= link_to reservation.vaccine.name, vaccine_path(reservation.vaccine) %></td>
        <td><%= reservation.user.email %></td>
        <td><%= reservation.date %></td>

        <% if reservation.status == 'Pending' %>
          <td>
            <%= link_to "Confirm", reservation_confirm_path(reservation.id), method: :patch, data: { confirm: "Are you sure you want to confirm this reservation?" }, class: 'btn btn-outline-success btn-sm' %>
            <%= link_to "Cancel", reservation_cancel_path(reservation.id), method: :patch, data: { confirm: "Are you sure you want to cancel this reservation?" }, class: 'btn btn-outline-danger btn-sm' %>
          </td>

        <% elsif reservation.status == 'Confirmed' %>
          <td>Confirmed</td>
        <% else %>
          <td>Cancelled</td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_reservations-table.html.erb
<h1>Your reservations</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Vaccine</th>
      <th scope="col">Date</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <th scope="row"><%= reservation.id %></th>
        <td><%= link_to reservation.vaccine.name, vaccine_path(reservation.vaccine) %></td>
        <td><%= reservation.date %></td>
        <td><%= reservation.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_vaccines-table.html.erb
<h1>Your listed vaccines</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Vaccine id</th>
      <th scope="col">Name</th>
    </tr>
  </thead>
  <tbody>
    <% @vaccines.each do |vaccine| %>
      <tr>
        <th scope="row"><%= vaccine.id %></th>
        <td><%= link_to vaccine.name, vaccine_path(vaccine) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/vaccines/dashboard.html.erb
<div class="container">

<!-- Temporary html, should make both of these sections into tables -->

  <div class="container" id='your-vaccines'>
    <%= render 'shared/vaccines-table' %>
  </div>

  <div class="container" id='your-vaccines'>
    <%= render 'shared/reservations-for-seller-table' %>
  </div>

  <div class="container" id="your-reservations">
    <%= render 'shared/reservations-table' %>
  </div>

</div>

app/views/vaccines/index.html.erb
<div class=content>
  <div class="cards">
    <ul>
      <% @vaccines.each do |vaccine| %>
        <div class="card-product">
          <% if vaccine.photo.attached? %>
            <%= cl_image_tag vaccine.photo.key, height: 300, width: 400, crop: :fill %>
          <% else %>
            <img src="https://source.unsplash.com/CMLL0UD6AEE/300x400">
          <% end %>
          <div class="card-product-infos">
            <h2><%= link_to vaccine.name, vaccine_path(vaccine) %></h2>
            <p><%= vaccine.description %></strong></p>
          </div>
        </div>
      <% end %>
    </ul>
  </div>
    <%= image_tag "mapbox.png", id:"map" %>
</div>

app/views/vaccines/new.html.erb
<div class="container">

    <div class="col-md-8">
      <h1>List a new vaccine</h1>
      <div>
      <%= simple_form_for @vaccine do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>

</div>